### PR TITLE
Release/4.1.1

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Bugfixing version 4 node.

## Changes

- [x] Fix incorrect events generated in the scheduler. #363  #374 
- [x] Bump node version to 4.1.0 (including #380)
- [x] Fix calculation of baking and delegation rewards by avoiding integer overflow. #373 
- [x] Fix calculation of block reward. #376
- [x] Fix removal of delegators in certain scenarios #386

## Depends on 
- [ ] https://github.com/Concordium/concordium-base/pull/163

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by abizjak** [comment]
@Bargsteen @EmilLa1 can you please check the parts of this related to the mac and windows installers. In particular
- versions are correct
- the updated genesis file is correct for the testnet genesis of June 13, 2022

**Review by EmilLa1 — CHANGES_REQUESTED** [review]
Versions look fine. Wrong genesis. It is the old testnet genesis that is currently committed.

EDIT: My bad. Genesis also looks fine.

**Review by EmilLa1 — APPROVED** [review]
Versions looks fine.
Genesis file is the correct one.

**Review by Bargsteen — APPROVED** [review]
Everything looks fine regarding the mac node.

**Comment by abizjak** [comment]
Changes in this PR were merged into main with the #387 PR.

**Pull request closed without merging**
